// React/src/components/ToDoItem.jsx
import React from 'react';

export default function ToDoItem({ toDo, onTodoItemCompleted, onTodoItemDeleted }) {

    return (
        <div>
            <input key={toDo.id} type="checkbox" onClick={onTodoItemCompleted} defaultChecked={toDo.completedDate} />
            <div>{toDo.text}</div>
            <div>
                {(toDo.completedDate) &&
                    <span>
                        {new Date(toDo.completedDate).toDateString()}
                    </span>
                }
            </div>
            <input type="button" className="btn-sm btn-danger" onClick={onTodoItemDeleted} value="Delete" />
        </div>
    );
}

// angular/src/app/todo-item/todo-item.component.ts
import { Component, EventEmitter, Input, Output} from '@angular/core';
import { Todo } from '../todo';
import { TodoService } from '../todo.service';

@Component({
  selector: 'app-todo-item',
  templateUrl: './todo-item.component.html',
  styleUrls: ['./todo-item.component.css']
})
export class TodoItemComponent {
  @Input() todo!: Todo;
  @Output() onTodoChanged = new EventEmitter<Todo>();
  @Output() onTodoDeleted = new EventEmitter<number>();

  constructor(
    private todoService: TodoService,
  ) { }

  onCheckboxChange(todo: Todo): void {
    this.onTodoChanged.emit(todo);
  }

  onDeleteButtonClicked(todoId: number) {
    this.onTodoDeleted.emit(todoId);
  }
}

<div>
  <input type="checkbox" [checked]="todo.completedDate !== null" (change)="onCheckboxChange(todo)" />
  <div>{{todo.text}}</div>
  <div *ngIf="todo.completedDate">
    <span>
      {{todo.completedDate | date: 'short'}}
    </span>
    }
  </div>
  <input type="button" className="btn-sm btn-danger" (click)="onDeleteButtonClicked(todo.id)" value="Delete" />
</div>
